#!/usr/bin/env bash
IFS=

if [ ".$1" == "." ]; then

cat <<EOF
usage: addpath  -- add a file to the end of the PATH variable
  parms usage
   parm1
    null  - show this help info
    .     - place current pwd at end of PATH
    other - place other at end of PATH
   parm2
    nomsg - do not show msgs (before and after)
    other -        show msgs (before and after)

  note: other may or may not be a directory. PATH doesn't care.
EOF

else

    if [ ".$2" != ".nomsg" ]; then
    echo
    echo BEFORE
    echo
    echo $PATH
    echo
    fi

    if [ ".$1" == "." ]; then
    export PATH="$PATH:$PWD"
    else
    export PATH="$PATH:$1"
    fi

    if [ ".$2" != ".nomsg" ]; then
    echo
    echo AFTER
    echo
    echo $PATH
    fi
fi
