#!/usr/bin/env bash

if [ ".$rchjlp" == "." ]; then
  echo
  echo "The rchjlp variable is: NULL"
  echo
cat << EOF-var
  The value for \$rchjlp seems to be lost.  The script will be
terminated.  Reset \$rchjlp from your console - 'export rchjlp=xxx'
where xxx is the base name of your exection lib.  Try again, good luck.

EOF-var

exit 8      # now scram
else
  echo
  echo "The rchjlp variable is: $rchjlp"
  echo
fi

