#!/usr/bin/env bash
# function to copy at top and use ech0 (rather than ech1
function ech0 () {     # turn on debugging with  export ech0=ON
  if [ ".$ech0" == ".ON" ]; then
    echo $@
  fi  
}
ech0 "\$rchjlp = $rchjlp"
xx=$0
lead=`dirname $xx`
ech0 "lead = $lead"
ech0 $xx
bld_dir="$lead"
ech0 "bld_dir = $bld_dir"
# export ech0=ON
ech0 "ls -al $bld_dir/execdir"
ls -al $bld_dir/execdir
ech0 "ls -al $bld_dir/builddir"
ls -al $bld_dir/builddir
# export ech0=off
read edir rest < $bld_dir/execdir
read bdir rest < $bld_dir/builddir
ech0 "bdir = $bdir"
ech0 "edir = $edir"
b_lib="$HOME/$bdir"
e_lib="$HOME/$edir"
echo
echo "\$rchjlp = $rchjlp"
echo "build-lib : $b_lib"
echo "exec-lib  : $e_lib"
  
if [ ! -e $e_lib ]; then
  echo
  echo "exec-lib : $e_lib  does NOT exist YET!"
fi
echo
echo
ech0 "\$rchjlp  indicates exec-lib is $HOME/$rchjlp"
ech0 "builddir indicates exec-lib is $HOME/$bdir"
p_lib=$HOME/$rchjlp

if [ ".$p_lib" != ".$e_lib" ]; then
  echo
  echo "===>> Mismatch Mismatch <<=========="
  echo "\$rchjlp ($rchjlp) should indicate $e_lib."
  echo "Please correct.  Use script rchjlp to change \$rchjlp."
  echo "Use your favorite editor to modify $b_lib/builddir."
else
  echo "Looks good."
fi
exit
