#!/usr/bin/env bash

if [ ".$1" == "." ]; then      # default provide info if no parms

cat << EOF_usage
usage: diffme parm1
function: to compare  $PWD/parm2 with parm1/parm2

No checking for parms or existence of files
EOF_usage

exit 0          # if needed

fi
the_mem=`basename $1`
echo "\$the_mem $the_mem"
echo diff $PWD/$the_mem  $1
diff $PWD/$the_mem  $1
drc=$?
echo "======================="
echo "comparison RC is $drc"
