#!/usr/bin/env bash

# function to copy at top and use ech0 (rather than ech1
function ech0 () {     # turn on debugging with  export ech0=ON
  if [ ".$ech0" == ".ON" ]; then
    echo $@
  fi  
}

ech0
ech0 "Did you issue 'export ech0=ON' before entry"
ech0 "If you see this msg you did. "
ech0

export ech0=ON

ech0
ech0 "ech0 was dynamically provided."
ech0

export ech0=anythingbut_ON

ech0 "Never see this."

ech0
echo "A real echo here"
echo "Before invoking  echotest1  "
echo " arm ech0 with 'export ech0=ON' "
echo " disarm ech0 with 'export ech0=anythingbut_ON' "
echo 
echo "At the start of a terminal session \$ech0 is likely NULL."
