#!/usr/bin/env bash

rchjlp="$1"
export rchjlp=$rchjlp

# function to copy at top and use ech0 (rather than ech1
function ech0 () {     # turn on debugging with  export ech0=ON
  if [ ".$ech0" == ".ON" ]; then
    echo $@
  fi  
}


if [ ".$rchjlp" == "." ]; then

cat << EOF_var

  The \$rchjlp is not available.  I suspect you FORGOT to add
the parm1 value. You should use  '. ~/exec-lib/engageq exec-lib'.

Alternatively you may use:
  cd exec-lib
  . rchjlp                (respond to prompt with exec-lib basenam
  . ~/exec-lib/engage

EOF_var

else

#rchjlp=$1
#export rchjlp=$rchjlp

the_dir=$HOME/$rchjlp     
read -r exec_base rest < $the_dir/execdir
read -r build_base rest < $the_dir/builddir

ech0 exec_base $exec_base
ech0 build_base $build_base

if [ -d $HOME/$rchjlp ]; then
  cd $HOME/$rchjlp
  . addpath0 $HOME/$rchjlp nomsg
else
  cd $HOME/$build_base
  . addpath0 $HOME/$build_base nomsg
fi

echo 
echo "How much Neanderthal blood do you have? - Robert C Hansen"
echo 
echo "The more they overthink the plumbing, the easier it is  "
echo "to stop up the drain. - Montgomery Scott "
echo 
echo 
echo "'Make it so!' - Jean-Luc Picard"
echo
echo
echo Your path is now:
echo $PATH
echo
echo "Special variable \$rchjlp="$rchjlp

fi


