#!/usr/bin/env bash

# function to copy at top and use ech0 (rather than ech1
function ech0 () {     # turn on debugging with  export ech0=ON
  if [ ".$ech0" == ".ON" ]; then
    echo $@
  fi  
}

# Notes and needs for this script
# 1. script f1 for this to call  ( like f with acrolist  f1_acrolist
# 2. file ~/bin/f1_acrolist   default
# 3. file ~/bin/acrofile_name   holds the member-name across calls
# 4. director ~/bin/ff_acrolist_dir  sub dir of acrolists
#

read exec_dir rest < ~/$rchjlp/execdir
read bld_dir rest < ~/$rchjlp/builddir

usage() {
  cat <<EOF
:: usage ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::  
Name: ff  found in $0
Description: driver for aternative-f routine where the acronym list
  is set as a member of ~/bin/ff_acrolist_dir/<member-name>
   
parm
  null - shows this help information and current value of member-name.
  .    - enter the new acronym list file
  on   - prompt(s) and set(s) the  ~/bin/ff_acrolist_dir/ member-name
  off  - clear the member-name
  otherwise acts like f with up to three parms.

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: usage :  
EOF
}

ech0 "exec-dir $exec_dir,  build-dir $bld_dir "
if [ ".$1" == "." ]; then
  usage
## touch $HOME/bin/ff_acroname
   touch $HOME/$exec_dir/ff_acroname


  nl=`wc $HOME/$exec_dir/ff_acroname |  awk '{print $1}'`

ech0 "nl $nl"

# This is first time code to set the environment.
  if [ ! -d ~/$exec_dir/ff_acrolist_dir ]; then
    mkdir ~/$rchjlp/ff_acrolist_dir
    mkdircc=$?
    ech0 "\$mkdircc = $mkdircc  "
    ls -A ~/$rchjlp/ff_acrolist_dir
    echo "firsttime" > ~/$exec_dir/ff_acroname 
    echo "# acro   filename" > ~/$exec_dir/ff_acrolist_dir/firsttime 
  fi

  if [ ".$nl" == ".0" ]; then
    acroname="firsttime"
#    echo "Current acrolist is ~/$exec_dir/ff_acrolist_dir/firstname"
  else
    acroname=`head -n1 $HOME/$rchjlp/ff_acroname | tail -n1`
  fi
  echo
  echo "$acroname - Current acrolist is ~/$exec_dir/ff_acrolist_dir/$acroname"
  echo
  echo "List of non-default current choices:"
##ls ~/bin/ff_acrolist_dir
  ls ~/$exec_dir/ff_acrolist_dir
## simple change  
  exit
fi

p1=$1
if [ ".$p1" == ".off" ]; then 
  p1="OFF"
fi

if [ ".$p1" == ".OFF" ]; then 
# rm $HOME/bin/ff_acroname               # clear by deleting
  rm $HOME/$exec_dir/ff_acroname               # clear by deleting
  sleep 1
# touch $HOME/bin/ff_acrofile_name          # reallocate empty
  touch $HOME/$exec_dir/ff_acrofile_name          # reallocate empty
#  nl=`wc $HOME/bin/acrofile_name`
#  ech0  $nl $nl
  exit 
fi


if [ ".$p1" == ".on" ]; then
  p1="ON" 
fi

if [ ".$p1" == ".ON" ]; then 
   echo -n "Enter the acrolist file name : "
   read answer   rest
   acroname=$answer  
#  echo $acroname > ~/bin/ff_acroname
   echo $acroname > ~/$exec_dir/ff_acroname
   echo "Using : "$acroname" for ff_acrofile_dir member name."
#  touch ~/bin/ff_acrolist_dir/$acroname
   touch ~/$exec_dir/ff_acrolist_dir/$acroname
   echo showing acroname
#  cat ~/bin/ff_acroname
   cat ~/$exec_lib/ff_acroname
   exit
fi
#echo acroparm is ">"$acroparm"<"

echo f1 $1 $2 $3
f1 $1 $2 $3


