#!/usr/bin/env bash

echo "Checking ..."
echo "\$rchjlp is $rchjlp"
read build_dir rest < $PWD/builddir
read exec_dir rest < $PWD/execdir

#echo "Execution lib dir is : "$HOME/$exec_dir
build_lib=$HOME/$build_dir
exec_lib=$HOME/$exec_dir 
echo "Build     lib dir is : "$HOME/$build_dir
echo "Execution lib dir is : "$exec_lib


function cpit () {
  echo "cp $1 $exec_lib/$1"
  cp $1 $exec_lib/$1
  copyrc=$?
  if [ $copyrc -eq 0 ]; then
    echo "$1 copied to "$exec_lib
  else
    echo "Boo Boo -- check $1"
  fi
}

if [ -d $exec_lib ]; then
  echo "$exec_lib exists. Please renameit."
  echo -n "Enter new subdirectory name (return to exit): "
  read newname rest
  if [ ".$newname" == "." ]; then
    echo "Nothing done, I quit."
    exit 4
  else
    echo "mv $exec_lib $HOME/$newname"  
    mv $exec_lib $HOME/$newname
    echo "OK, we are ready -- rerun the INSTALL script"
    exit 2
  fi
else
  echo "On we go, allocate, populate and rePATH  $exec_lib."
fi 

mkdir $exec_lib
ls -alh $exec_lib    
cd $build_lib                  # get to right dir to do work

echo "Your original PATH"
echo $PATH

cpit 11asummary            # file of one line summaries
cpit addpath               # put file a end of PATH
cpit al                    # some semi-useful aliases
cpit addpath0              # put file at start of PATH
cpit builddir              # hold build director basename
cpit c                     # director quick change by acronym
cpit checksys              # aid to show rchjlp, bld-lib exec-lib
cpit checkvar              # aid to show rchjlp
cpit chkvar                # check the rchjlp variable        
cpit COPYING               # MIT license
cpit delpath               # remove file from PATH 
cpit dirinpath             # chk all dir file where in path
cpit ech0                  # debugging echo function
cpit ech1                  # debugging echo inline
cpit execdir               # hold execution dir basename
cpit engage                # hook in code to activate environment
cpit f                     # go to file by acronym
cpit f_acrolist            # start list of acronyms
cpit g                     # go to file by number
cpit ged                   # like g but with nano rather than vim
# not this one -- cpit INSTALL               # this script
cpit lbang                 # for the lazy -  #!/usr/bin/env bash
cpit meminpath             # show which path files have mem (compare
cpit refresh               # copy a new version from build to exec  
# not this one -- cpit setvar                # set the rchjlp                         
cpit src                   # Eric Raymond  Simple Revision Control  
cpit srcdoc                # starter notes on src                  
cpit showpath              # show the path files
cpit wrsum                 # document aid tool  

ls -alh $exec_lib

echo "To activate enter  '. ~/$rchjlp/engage' "
echo "You can back off with '. unpath $exec_lib' "
echo "Restart with existing rchtest file with  . ~/$rchjlp/engage"
echo 
echo "Good Luck"
