#!/usr/bin/env bash

if [ ".$1" == "." ]; then      # default provide info if no parms

cat << EOF_usage
usage: rchjlp - this is an aid to set the \$rchjlp variable
syntal:  . rchjlp parm1

parm1: NULL will lead to a prompt for \$rchjlp
       other - \$1 will be used for \$rchjlp  (help not shown)

EOF_usage
echo -n "Please enter the desire value for \$rchjlp :"
read wi_parm rest

else

wi_parm=$1

fi

echo "You may also give '. export rchjlp=$wi_parm' by hand."
export rchjlp=$wi_parm

echo "Just checking  \$rchjlp : "$rchjlp
