#!/usr/bin/env bash

if [ ".$1" == "." ]; then

cat << EOF-usage
usage: re_build parm1 parm2
function: copy a member to build-lib (name will remain the same).
  parm1 - name of member to copy
  parm2 - .     - the sending lib will be from pwd ( \$PWD/\$parm1 )
          other - the sending lib will be the exec-lib.

  the cp command will be shown and confirmation is 'y' or 'Y'.

EOF-usage

exit 4
fi

# better version coming

read -r bld_dir rest < $HOME/$rchjlp/builddir
read -r exec_dir rest < $HOME/$rchjlp/execdir

# check to see if sending member exists.
if [ ".$2" == ".." ]; then
  if [ ! -e $PWD/$1 ] ; then
    echo "$PWD/$1 does NOT EXIST."
    echo "Therefore, I quit. Nothing done."
    exit 8
   fi
else
  if [ ! -e $HOME/$exec_dir/$1 ] ; then
    echo "$HOME/$exec_dir/$1 does NOT EXIST."
    echo "Therefore, I quit. Nothing done."
    exit 8
   fi
fi

# Display the command to be executed.
if [ ".$2" == ".." ]; then
  echo cp -vp $PWD/$1 $HOME/$bld_dir/$1
else
  echo cp -vp $HOME/$exec_dir/$1 $HOME/$bld_dir/$1
fi

echo
echo -n "Is this OK? y/Y to approve: "
read answer rest

# Execute the command on 'y' or 'Y'
if [ ".$answer" == ".y" ] || [ ".$answer" == ".Y" ]; then
    if [ ".$2" == ".." ]; then
      cp -vp $PWD/$1 $HOME/$bld_dir/$1
    else
      cp -vp $HOME/$exec_dir/$1 $HOME/$bld_dir/$1
    fi
else
  echo "Answer ($answer) NOT 'y' or 'Y', Nothing done, I quit."
fi

