#!/usr/bin/env bash

back=".back"

exec_back=$rchbls$back

if [ -d $rchbls ]; then
  echo "$rchbls EXISTs"
else
  echo "$rchbls DOES NOT Exist."
  echo "Quiting, you must reinstall"
  exit
fi

if [ -d $exec_back ]; then
  echo "$exec_back EXISTs"
  echo "Backup already exists!!"
  echo "Quiting no work done."
  exit
else
  echo "$exec_back DOES NOT Exist."
fi
read -r my_exec rest < $rchbls/execdir
read -r my_build rest < $rchbls/builddir
mv $rchbls $exec_back -v

if [ -d $rchbls ] && [ -d $exec_back ]; then

cat << EOF-bk
$rchbls EXISTs.
$exec_back EXISTS.

This 'refresh' script will make a backup of $rchbls it
 1. Move $rchbls to $exec_back as a backup.
 2. Reallocate the $rchbls directory.
 3. reestablish necessary first word in builddir and execdir.
 4. recopy rest of $rchbls members.

EOF-bk

echo test exit
fi

if [ -d $rchbls ]; then
  echo "Moving $rchbls to $exec_back for backup."
  mv $rchbls $exec_back
  moverc=$?
  if [ $moverc -eq 0 ]; then
    echo "Move/Backup sucessful."
  fi
fi

mkdir $rchbls

echo $my_exec > $rchbls/execdir
date >> $rchbls/execdir
echo "Refresh exec-lib name" >> $rchbls/execdir

echo $my_build > $rchbls/builddir
echo  test exit 2
while read -r line_item  ; do

  IFSsave=$IFS
  IFS=" "
  read -r filename rest <<< $line_item
  IFS=$IFSsave
  if [ ".${filename:0:1}" != ".#" ]; then
    echo "==copy it:: $line_item"
    echo "_           cp -vp $filename  $rchbls/$filename"
    cp -vp $my_build/$filename  $rchbls/$filename
    copyrc=$?
    echo "_           Copy ret code was $copyrc"
    if [ $copyrc -ne 0 ]; then
      echo "ERROR in $filename COPY !!! "
      echo "refresh script stops here."
      echo "Please resolve and rerun."
      echo "you probably will want to keep $exec_back"
      echo "If so then  'rm -vfr $rchbls'  "
      exit 8
    fi
  else
    echo "A comment:: $line_item"
  fi
done < $my_build/INSTALLmbrs

echo " DONE DONE DONE ---- finally."
echo " gold star for patience."
echo
echo "You can see difference by"
echo "  diff $rchbls  $exec_back"

exit 0          # if needed
