#!/usr/bin/env bash

# better version coming

echo cp -v $HOME/rchbuild/$1 $HOME/rchtest/$1

echo
echo -n "Is this OK? y/Y to approve: "
read answer rest

if [ ".$answer" == ".y" ] || [ ".$answer" == ".Y" ]; then
  cp -v $HOME/rchbuild/$1 $HOME/rchtest/$1
else
  echo "Answer NOT 'y' or 'Y', Nothing done, I quit."
fi
